# Generated by Django 5.1.3 on 2024-11-19 00:20

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("wagtailcore", "0094_alter_page_locale"),
        ("wagtailimages", "0027_image_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="NewsIndexPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "body",
                    wagtail.fields.StreamField(
                        [("paragraph", 0), ("h2", 1), ("h3", 2), ("h4", 3), ("h5", 4)],
                        blank=True,
                        block_lookup={
                            0: ("wagtail.blocks.RichTextBlock", (), {}),
                            1: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"icon": "title", "template": "base/blocks/h2.html"},
                            ),
                            2: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"icon": "title", "template": "base/blocks/h3.html"},
                            ),
                            3: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"icon": "title", "template": "base/blocks/h4.html"},
                            ),
                            4: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"icon": "title", "template": "base/blocks/h5.html"},
                            ),
                        },
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="NewsPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "body",
                    wagtail.fields.StreamField(
                        [("paragraph", 0), ("h2", 1), ("h3", 2), ("h4", 3), ("h5", 4)],
                        blank=True,
                        block_lookup={
                            0: ("wagtail.blocks.RichTextBlock", (), {}),
                            1: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"icon": "title", "template": "base/blocks/h2.html"},
                            ),
                            2: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"icon": "title", "template": "base/blocks/h3.html"},
                            ),
                            3: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"icon": "title", "template": "base/blocks/h4.html"},
                            ),
                            4: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"icon": "title", "template": "base/blocks/h5.html"},
                            ),
                        },
                    ),
                ),
                ("excerpt", wagtail.fields.RichTextField(blank=True)),
                (
                    "thumbnail",
                    models.ForeignKey(
                        blank=True,
                        help_text="Image to display for the story",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
    ]
