# Generated by Django 5.1.3 on 2024-11-21 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0002_newslistingsettings"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newslistingsettings",
            name="paginate_by",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
