# Generated by Django 5.1.3 on 2024-11-21 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0003_alter_newslistingsettings_paginate_by"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newslistingsettings",
            name="paginate_by",
            field=models.PositiveSmallIntegerField(
                blank=True, help_text="Defaults to 5 when not set.", null=True
            ),
        ),
    ]
