# Generated by Django 5.0.9 on 2024-12-10 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0006_rename_alt_text_newspage_thumbnail_alt_text_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="newspage",
            name="thumbnail_alt_text",
        ),
    ]
