# Generated by Django 5.0.9 on 2024-12-11 03:13

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0007_remove_newspage_thumbnail_alt_text"),
        ("wagtailimages", "0027_image_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newspage",
            name="excerpt",
            field=wagtail.fields.RichTextField(
                blank=True,
                help_text="Text to display on the news index page. Defaults to a truncation of the body.",
            ),
        ),
        migrations.AlterField(
            model_name="newspage",
            name="thumbnail",
            field=models.ForeignKey(
                blank=True,
                help_text="Image to display for the story. Alt text is defined when editing the image itself.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
            ),
        ),
    ]
