# Generated by Django 5.1.3 on 2024-11-19 00:20

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_create_homepage"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepage",
            name="body",
            field=wagtail.fields.StreamField(
                [("paragraph", 0), ("h2", 1), ("h3", 2), ("h4", 3), ("h5", 4)],
                blank=True,
                block_lookup={
                    0: ("wagtail.blocks.RichTextBlock", (), {}),
                    1: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"icon": "title", "template": "base/blocks/h2.html"},
                    ),
                    2: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"icon": "title", "template": "base/blocks/h3.html"},
                    ),
                    3: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"icon": "title", "template": "base/blocks/h4.html"},
                    ),
                    4: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"icon": "title", "template": "base/blocks/h5.html"},
                    ),
                },
            ),
        ),
    ]
