# Generated by Django 5.0.9 on 2024-12-11 03:13

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_homepage_body"),
        ("wagtailimages", "0027_image_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepage",
            name="cta_background_image",
            field=models.ForeignKey(
                blank=True,
                help_text="Image to display as a background for the Call to Action. Mind the contrast, and for different screen sizes.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="cta_button_link",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="homepage",
            name="cta_button_text",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="homepage",
            name="cta_heading",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="homepage",
            name="cta_text",
            field=wagtail.fields.RichTextField(blank=True),
        ),
    ]
