# Generated by Django 5.0.9 on 2024-12-12 22:10

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0004_homepage_cta_background_image_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepage",
            name="sections",
            field=wagtail.fields.StreamField(
                [("section", 3)],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Section heading", "required": True},
                    ),
                    1: ("wagtail.blocks.PageChooserBlock", (), {"required": True}),
                    2: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {
                            "help_text": "Number of child pages to show",
                            "required": True,
                        },
                    ),
                    3: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 0), ("page", 1), ("count", 2)]],
                        {},
                    ),
                },
            ),
        ),
    ]
