# Generated by Django 5.0.9 on 2024-12-17 02:35

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0007_homepage_cta_button_page_and_more"),
        ("wagtailcore", "0094_alter_page_locale"),
        ("wagtailimages", "0027_image_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepage",
            name="cta_darken_image",
            field=models.BooleanField(
                default=False,
                help_text="Check this box to add an overlay to the background image to darken it by 20%.",
                verbose_name="Darken background image?",
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="cta_background_image",
            field=models.ForeignKey(
                blank=True,
                help_text="Image to display as a background for the Call to Action. Mind the contrast, and for different screen sizes.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
                verbose_name="CTA section background image.",
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="cta_button_link",
            field=models.URLField(
                blank=True,
                help_text="Overrides the page link.",
                verbose_name="Button external link override",
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="cta_button_page",
            field=models.ForeignKey(
                blank=True,
                help_text="Link to apply to the button. Link to internal pages using this, or override it with the Button Link for external links.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailcore.page",
                verbose_name="Button internal page link",
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="cta_button_text",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Button Text"
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="cta_heading",
            field=models.CharField(blank=True, max_length=100, verbose_name="Heading"),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="cta_text",
            field=wagtail.fields.RichTextField(blank=True, verbose_name="Text"),
        ),
    ]
