# Generated by Django 5.0.9 on 2024-12-18 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0008_homepage_cta_darken_image_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="homepage",
            name="show_nested_children",
            field=models.BooleanField(
                default=True, help_text="Check this to display nested child pages."
            ),
        ),
    ]
