# Generated by Django 5.0.9 on 2025-12-10 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0012_homepage_cta_show_search"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepage",
            name="show_interactive_diagram",
            field=models.BooleanField(
                default=False,
                help_text="Check this box to display the interactive research data lifecycle diagram on this page. The diagram is customizable in Settings > Interactive Diagram Settings. This interactive diagram provides an accessible, visual representation of the research lifecycle phases.",
                verbose_name="Show Interactive Diagram",
            ),
        ),
    ]
