# Generated by Django 5.0.9 on 2024-12-13 02:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0002_standardpage_nested_children_depth_and_more"),
        ("services", "0002_servicepage_nested_children_depth_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="standardpage",
            name="associated_research_lifecycle_phase",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="services.researchlifecyclephase",
            ),
        ),
    ]
