# Generated by Django 5.0.9 on 2024-12-18 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0003_standardpage_associated_research_lifecycle_phase"),
    ]

    operations = [
        migrations.AlterField(
            model_name="standardpage",
            name="show_nested_children",
            field=models.BooleanField(
                default=True, help_text="Check this to display nested child pages."
            ),
        ),
    ]
