# Generated by Django 5.0.9 on 2025-01-24 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0007_floatingfooterbutton"),
    ]

    operations = [
        migrations.AddField(
            model_name="floatingfooterbutton",
            name="text",
            field=models.CharField(
                blank=True, help_text="Text to display on the button", max_length=255
            ),
        ),
    ]
