# Generated by Django 5.0.9 on 2025-12-10 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0008_floatingfooterbutton_text"),
    ]

    operations = [
        migrations.CreateModel(
            name="InteractiveDiagram",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        default="Research Data Lifecycle",
                        help_text="Mandatory title for accessibility purposes. This will be read by screen readers.",
                        max_length=255,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        default="The research data lifecycle represents the phases of the research data process. The research data lifecycle is one part of the overall research process, and, just as the research process is iterative, so too is the research data lifecycle: each component builds upon the next, and moving between phases is a natural part of the overall research process.",
                        help_text="Mandatory description for accessibility purposes. This will be read by screen readers. Consider including information that is passed visually in the diagram.",
                    ),
                ),
                (
                    "font_size",
                    models.DecimalField(
                        decimal_places=1,
                        default=14.0,
                        help_text="Font size for diagram text in pixels. Recommended range: 10.0 to 18.0, but any value is allowed.",
                        max_digits=4,
                    ),
                ),
                (
                    "phase1_text",
                    models.CharField(default="Plan & Design", max_length=100),
                ),
                (
                    "phase1_link",
                    models.CharField(
                        default="/research-lifecycle/plan-design/", max_length=255
                    ),
                ),
                (
                    "phase1_fill_color",
                    models.CharField(default="#800000", max_length=7),
                ),
                (
                    "phase1_text_color",
                    models.CharField(default="#ffffff", max_length=7),
                ),
                (
                    "phase2_text",
                    models.CharField(default="Collect & Create", max_length=100),
                ),
                (
                    "phase2_link",
                    models.CharField(
                        default="/research-lifecycle/collect-create/", max_length=255
                    ),
                ),
                (
                    "phase2_fill_color",
                    models.CharField(default="#a9431e", max_length=7),
                ),
                (
                    "phase2_text_color",
                    models.CharField(default="#ffffff", max_length=7),
                ),
                (
                    "phase3_text",
                    models.CharField(default="Analyze & Collaborate", max_length=100),
                ),
                (
                    "phase3_link",
                    models.CharField(
                        default="/research-lifecycle/analyze-collaborate/",
                        max_length=255,
                    ),
                ),
                (
                    "phase3_fill_color",
                    models.CharField(default="#404040", max_length=7),
                ),
                (
                    "phase3_text_color",
                    models.CharField(default="#ffffff", max_length=7),
                ),
                (
                    "phase4_text",
                    models.CharField(default="Evaluate & Archive", max_length=100),
                ),
                (
                    "phase4_link",
                    models.CharField(
                        default="/research-lifecycle/evaluate-archive/", max_length=255
                    ),
                ),
                (
                    "phase4_fill_color",
                    models.CharField(default="#a9431e", max_length=7),
                ),
                (
                    "phase4_text_color",
                    models.CharField(default="#ffffff", max_length=7),
                ),
                ("phase5_text", models.CharField(default="Share", max_length=100)),
                (
                    "phase5_link",
                    models.CharField(
                        default="/research-lifecycle/share/", max_length=255
                    ),
                ),
                (
                    "phase5_fill_color",
                    models.CharField(default="#404040", max_length=7),
                ),
                (
                    "phase5_text_color",
                    models.CharField(default="#ffffff", max_length=7),
                ),
                (
                    "phase6_text",
                    models.CharField(default="Publish & Reuse", max_length=100),
                ),
                (
                    "phase6_link",
                    models.CharField(
                        default="/research-lifecycle/publish-reuse/", max_length=255
                    ),
                ),
                (
                    "phase6_fill_color",
                    models.CharField(default="#a9431e", max_length=7),
                ),
                (
                    "phase6_text_color",
                    models.CharField(default="#ffffff", max_length=7),
                ),
                (
                    "phase7_text",
                    models.CharField(default="Store & Manage", max_length=100),
                ),
                (
                    "phase7_link",
                    models.CharField(
                        default="/research-lifecycle/store-manage/", max_length=255
                    ),
                ),
                (
                    "phase7_fill_color",
                    models.CharField(default="#d9d9d9", max_length=7),
                ),
                (
                    "phase7_text_color",
                    models.CharField(default="#000000", max_length=7),
                ),
            ],
            options={
                "verbose_name": "Interactive Diagram Settings",
                "verbose_name_plural": "Interactive Diagram Settings",
            },
        ),
        migrations.AddField(
            model_name="standardpage",
            name="show_interactive_diagram",
            field=models.BooleanField(
                default=False,
                help_text="Check this box to display the interactive research data lifecycle diagram on this page. The diagram is customizable in Settings > Interactive Diagram Settings. This interactive diagram provides an accessible, visual representation of the research lifecycle phases.",
                verbose_name="Show Interactive Diagram",
            ),
        ),
    ]
