# Generated by Django 5.0.9 on 2025-12-09 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0008_floatingfooterbutton_text"),
    ]

    operations = [
        migrations.CreateModel(
            name="InteractiveDiagram",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        default="Research Data Lifecycle",
                        help_text="Mandatory title for accessibility purposes. This will be read by screen readers.",
                        max_length=255,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        default="The research data lifecycle represents the phases of the research data process. The research data lifecycle is one part of the overall research process, and, just as the research process is iterative, so too is the research data lifecycle: each component builds upon the next, and moving between phases is a natural part of the overall research process.",
                        help_text="Mandatory description for accessibility purposes. This will be read by screen readers.",
                    ),
                ),
                (
                    "font_size",
                    models.DecimalField(
                        decimal_places=1,
                        default=14.0,
                        help_text="Font size for diagram text in pixels. Range: 10.0 to 18.0 in 0.5 increments.",
                        max_digits=3,
                    ),
                ),
                (
                    "phase1_text",
                    models.CharField(
                        default="Plan & Design",
                        help_text="Text for Phase 1. Keep text short to fit in the box.",
                        max_length=100,
                    ),
                ),
                (
                    "phase1_link",
                    models.CharField(
                        default="/research-lifecycle/plan-design/",
                        help_text="Link for Phase 1. Format: /path/to/page/ or https://example.com",
                        max_length=255,
                    ),
                ),
                (
                    "phase1_fill_color",
                    models.CharField(
                        default="#800000",
                        help_text="Hex color code for Phase 1 fill (e.g., #800000 for maroon)",
                        max_length=7,
                    ),
                ),
                (
                    "phase1_text_color",
                    models.CharField(
                        default="#ffffff",
                        help_text="Hex color code for Phase 1 text (e.g., #ffffff for white)",
                        max_length=7,
                    ),
                ),
                (
                    "phase2_text",
                    models.CharField(
                        default="Collect & Create",
                        help_text="Text for Phase 2. Keep text short to fit in the box.",
                        max_length=100,
                    ),
                ),
                (
                    "phase2_link",
                    models.CharField(
                        default="/research-lifecycle/collect-create/",
                        help_text="Link for Phase 2. Format: /path/to/page/ or https://example.com",
                        max_length=255,
                    ),
                ),
                (
                    "phase2_fill_color",
                    models.CharField(
                        default="#a9431e",
                        help_text="Hex color code for Phase 2 fill (e.g., #800000 for maroon)",
                        max_length=7,
                    ),
                ),
                (
                    "phase2_text_color",
                    models.CharField(
                        default="#ffffff",
                        help_text="Hex color code for Phase 2 text (e.g., #ffffff for white)",
                        max_length=7,
                    ),
                ),
                (
                    "phase3_text",
                    models.CharField(
                        default="Analyze & Collaborate",
                        help_text="Text for Phase 3. Keep text short to fit in the box.",
                        max_length=100,
                    ),
                ),
                (
                    "phase3_link",
                    models.CharField(
                        default="/research-lifecycle/analyze-collaborate/",
                        help_text="Link for Phase 3. Format: /path/to/page/ or https://example.com",
                        max_length=255,
                    ),
                ),
                (
                    "phase3_fill_color",
                    models.CharField(
                        default="#404040",
                        help_text="Hex color code for Phase 3 fill (e.g., #800000 for maroon)",
                        max_length=7,
                    ),
                ),
                (
                    "phase3_text_color",
                    models.CharField(
                        default="#ffffff",
                        help_text="Hex color code for Phase 3 text (e.g., #ffffff for white)",
                        max_length=7,
                    ),
                ),
                (
                    "phase4_text",
                    models.CharField(
                        default="Evaluate & Archive",
                        help_text="Text for Phase 4. Keep text short to fit in the box.",
                        max_length=100,
                    ),
                ),
                (
                    "phase4_link",
                    models.CharField(
                        default="/research-lifecycle/evaluate-archive/",
                        help_text="Link for Phase 4. Format: /path/to/page/ or https://example.com",
                        max_length=255,
                    ),
                ),
                (
                    "phase4_fill_color",
                    models.CharField(
                        default="#a9431e",
                        help_text="Hex color code for Phase 4 fill (e.g., #800000 for maroon)",
                        max_length=7,
                    ),
                ),
                (
                    "phase4_text_color",
                    models.CharField(
                        default="#ffffff",
                        help_text="Hex color code for Phase 4 text (e.g., #ffffff for white)",
                        max_length=7,
                    ),
                ),
                (
                    "phase5_text",
                    models.CharField(
                        default="Share",
                        help_text="Text for Phase 5. Keep text short to fit in the box.",
                        max_length=100,
                    ),
                ),
                (
                    "phase5_link",
                    models.CharField(
                        default="/research-lifecycle/share/",
                        help_text="Link for Phase 5. Format: /path/to/page/ or https://example.com",
                        max_length=255,
                    ),
                ),
                (
                    "phase5_fill_color",
                    models.CharField(
                        default="#404040",
                        help_text="Hex color code for Phase 5 fill (e.g., #800000 for maroon)",
                        max_length=7,
                    ),
                ),
                (
                    "phase5_text_color",
                    models.CharField(
                        default="#ffffff",
                        help_text="Hex color code for Phase 5 text (e.g., #ffffff for white)",
                        max_length=7,
                    ),
                ),
                (
                    "phase6_text",
                    models.CharField(
                        default="Publish & Reuse",
                        help_text="Text for Phase 6. Keep text short to fit in the box.",
                        max_length=100,
                    ),
                ),
                (
                    "phase6_link",
                    models.CharField(
                        default="/research-lifecycle/publish-reuse/",
                        help_text="Link for Phase 6. Format: /path/to/page/ or https://example.com",
                        max_length=255,
                    ),
                ),
                (
                    "phase6_fill_color",
                    models.CharField(
                        default="#a9431e",
                        help_text="Hex color code for Phase 6 fill (e.g., #800000 for maroon)",
                        max_length=7,
                    ),
                ),
                (
                    "phase6_text_color",
                    models.CharField(
                        default="#ffffff",
                        help_text="Hex color code for Phase 6 text (e.g., #ffffff for white)",
                        max_length=7,
                    ),
                ),
                (
                    "phase7_text",
                    models.CharField(
                        default="Store & Manage",
                        help_text="Text for Phase 7. Keep text short to fit in the box.",
                        max_length=100,
                    ),
                ),
                (
                    "phase7_link",
                    models.CharField(
                        default="/research-lifecycle/store-manage/",
                        help_text="Link for Phase 7. Format: /path/to/page/ or https://example.com",
                        max_length=255,
                    ),
                ),
                (
                    "phase7_fill_color",
                    models.CharField(
                        default="#d9d9d9",
                        help_text="Hex color code for Phase 7 fill (e.g., #800000 for maroon)",
                        max_length=7,
                    ),
                ),
                (
                    "phase7_text_color",
                    models.CharField(
                        default="#000000",
                        help_text="Hex color code for Phase 7 text (e.g., #ffffff for white)",
                        max_length=7,
                    ),
                ),
            ],
            options={
                "verbose_name": "Interactive Diagram Settings",
            },
        ),
        migrations.AddField(
            model_name="standardpage",
            name="show_interactive_diagram",
            field=models.BooleanField(
                default=False,
                help_text="Check this box to display the interactive research data lifecycle diagram on this page. The diagram is customizable in Settings > Interactive Diagram Settings. This interactive diagram provides an accessible, visual representation of the research lifecycle phases.",
                verbose_name="Show Interactive Diagram",
            ),
        ),
    ]
