# Generated by Django 5.0.9 on 2025-12-12 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0009_interactivediagram_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="interactivediagram",
            name="description",
            field=models.TextField(
                default="This diagram represents a continuous research data lifecycle composed of seven sequential phases arranged in a circle, \n        while the seventh phase is centered within the circle and present throughout.\n        Each wedge is a button that leads to a detailed page for that phase. \n        The circular layout communicates that once the final phase is reached, the process loops back to the first.\n        ",
                help_text="Mandatory description for accessibility purposes. This will be read by screen readers. Describe the purpose and meaning of the diagram's visual concepts.",
            ),
        ),
    ]
