# Generated by Django 5.0.9 on 2025-12-09 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0009_interactivediagram_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="interactivediagram",
            options={
                "verbose_name": "Interactive Diagram Settings",
                "verbose_name_plural": "Interactive Diagram Settings",
            },
        ),
        migrations.AlterField(
            model_name="interactivediagram",
            name="font_size",
            field=models.DecimalField(
                decimal_places=1,
                default=14.0,
                help_text="Font size for diagram text in pixels. Recommended range: 10.0 to 18.0, but any value is allowed.",
                max_digits=4,
            ),
        ),
        migrations.AlterField(
            model_name="interactivediagram",
            name="phase1_fill_color",
            field=models.CharField(default="#800000", max_length=7),
        ),
        migrations.AlterField(
            model_name="interactivediagram",
            name="phase1_link",
            field=models.CharField(
                default="/research-lifecycle/plan-design/", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="interactivediagram",
            name="phase1_text",
            field=models.CharField(default="Plan & Design", max_length=100),
        ),
        migrations.AlterField(
            model_name="interactivediagram",
            name="phase1_text_color",
            field=models.CharField(default="#ffffff", max_length=7),
        ),
        migrations.AlterField(
            model_name="interactivediagram",
            name="phase2_fill_color",
            field=models.CharField(default="#a9431e", max_length=7),
        ),
        migrations.AlterField(
            model_name="interactivediagram",
            name="phase2_link",
            field=models.CharField(
                default="/research-lifecycle/collect-create/", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="interactivediagram",
            name="phase2_text",
            field=models.CharField(default="Collect & Create", max_length=100),
        ),
        migrations.AlterField(
            model_name="interactivediagram",
            name="phase2_text_color",
            field=models.CharField(default="#ffffff", max_length=7),
        ),
        migrations.AlterField(
            model_name="interactivediagram",
            name="phase3_fill_color",
            field=models.CharField(default="#404040", max_length=7),
        ),
        migrations.AlterField(
            model_name="interactivediagram",
            name="phase3_link",
            field=models.CharField(
                default="/research-lifecycle/analyze-collaborate/", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="interactivediagram",
            name="phase3_text",
            field=models.CharField(default="Analyze & Collaborate", max_length=100),
        ),
        migrations.AlterField(
            model_name="interactivediagram",
            name="phase3_text_color",
            field=models.CharField(default="#ffffff", max_length=7),
        ),
        migrations.AlterField(
            model_name="interactivediagram",
            name="phase4_fill_color",
            field=models.CharField(default="#a9431e", max_length=7),
        ),
        migrations.AlterField(
            model_name="interactivediagram",
            name="phase4_link",
            field=models.CharField(
                default="/research-lifecycle/evaluate-archive/", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="interactivediagram",
            name="phase4_text",
            field=models.CharField(default="Evaluate & Archive", max_length=100),
        ),
        migrations.AlterField(
            model_name="interactivediagram",
            name="phase4_text_color",
            field=models.CharField(default="#ffffff", max_length=7),
        ),
        migrations.AlterField(
            model_name="interactivediagram",
            name="phase5_fill_color",
            field=models.CharField(default="#404040", max_length=7),
        ),
        migrations.AlterField(
            model_name="interactivediagram",
            name="phase5_link",
            field=models.CharField(
                default="/research-lifecycle/share/", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="interactivediagram",
            name="phase5_text",
            field=models.CharField(default="Share", max_length=100),
        ),
        migrations.AlterField(
            model_name="interactivediagram",
            name="phase5_text_color",
            field=models.CharField(default="#ffffff", max_length=7),
        ),
        migrations.AlterField(
            model_name="interactivediagram",
            name="phase6_fill_color",
            field=models.CharField(default="#a9431e", max_length=7),
        ),
        migrations.AlterField(
            model_name="interactivediagram",
            name="phase6_link",
            field=models.CharField(
                default="/research-lifecycle/publish-reuse/", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="interactivediagram",
            name="phase6_text",
            field=models.CharField(default="Publish & Reuse", max_length=100),
        ),
        migrations.AlterField(
            model_name="interactivediagram",
            name="phase6_text_color",
            field=models.CharField(default="#ffffff", max_length=7),
        ),
        migrations.AlterField(
            model_name="interactivediagram",
            name="phase7_fill_color",
            field=models.CharField(default="#d9d9d9", max_length=7),
        ),
        migrations.AlterField(
            model_name="interactivediagram",
            name="phase7_link",
            field=models.CharField(
                default="/research-lifecycle/store-manage/", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="interactivediagram",
            name="phase7_text",
            field=models.CharField(default="Store & Manage", max_length=100),
        ),
        migrations.AlterField(
            model_name="interactivediagram",
            name="phase7_text_color",
            field=models.CharField(default="#000000", max_length=7),
        ),
    ]
